# Generated by Django 2.2.5 on 2019-09-28 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('code_dep', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name_dep', models.CharField(max_length=16, unique=True)),
                ('supervisor_dep', models.CharField(max_length=8, null=True)),
                ('superior_dep', models.CharField(max_length=8, null=True)),
                ('duty_dep', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('code_pos', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name_pos', models.CharField(max_length=32, unique=True)),
                ('duty_pos', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'positions',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_emp', models.CharField(max_length=32)),
                ('id_num_emp', models.CharField(max_length=18, unique=True)),
                ('tel_num_emp', models.CharField(max_length=12, unique=True)),
                ('supervisor_emp', models.IntegerField()),
                ('entry_date_emp', models.DateField()),
                ('ecp_emp', models.CharField(max_length=16, null=True)),
                ('ecpt_emp', models.CharField(max_length=12, null=True)),
                ('email_emp', models.CharField(max_length=64, null=True)),
                ('wechat_emp', models.CharField(max_length=64, null=True)),
                ('address_emp', models.CharField(max_length=128, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaching_app.Departments')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaching_app.Positions')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cla', models.CharField(max_length=32)),
                ('room_cla', models.CharField(max_length=32)),
                ('start_date_cla', models.DateField()),
                ('week_day_cla', models.CharField(choices=[('1', '星期一'), ('2', '星期二'), ('3', '星期三'), ('4', '星期四'), ('5', '星期五'), ('6', '星期六'), ('0', '星期日')], max_length=1)),
                ('master_cla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='master_emp', to='teaching_app.Employee')),
                ('teacher_cla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_emp', to='teaching_app.Employee')),
            ],
            options={
                'db_table': 'classes',
            },
        ),
    ]
