# Generated by Django 2.2.5 on 2019-10-20 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id_cam', models.AutoField(primary_key=True, serialize=False)),
                ('name_cam', models.CharField(max_length=32, verbose_name='名字')),
                ('address_cam', models.CharField(max_length=64, verbose_name='地址')),
                ('phone_cam', models.CharField(max_length=16, verbose_name='电话')),
                ('comment_cam', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'campus',
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cla', models.CharField(max_length=32)),
                ('number_stu_cla', models.SmallIntegerField()),
                ('start_date_cla', models.DateField()),
                ('week_day_cla', models.CharField(choices=[('1', '星期一'), ('2', '星期二'), ('3', '星期三'), ('4', '星期四'), ('5', '星期五'), ('6', '星期六'), ('0', '星期日')], max_length=1)),
                ('state_cla', models.CharField(choices=[('1', '未开课'), ('2', '开课中'), ('3', '已结课')], max_length=1)),
            ],
            options={
                'db_table': 'classes',
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id_cc', models.AutoField(primary_key=True, serialize=False)),
                ('name_cc', models.CharField(max_length=32)),
                ('stage_cc', models.CharField(max_length=16)),
                ('amount_cc', models.SmallIntegerField()),
                ('comment_cc', models.CharField(max_length=64, null=True)),
            ],
            options={
                'db_table': 'course_category',
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('code_dep', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='代码')),
                ('name_dep', models.CharField(max_length=16, unique=True, verbose_name='名字')),
                ('superior_dep', models.CharField(blank=True, max_length=8, null=True, verbose_name='上级部门')),
                ('duty_dep', models.CharField(max_length=128, verbose_name='职责')),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id_les', models.AutoField(primary_key=True, serialize=False)),
                ('order_les', models.SmallIntegerField()),
                ('name_les', models.CharField(max_length=32)),
                ('path_les', models.CharField(max_length=256)),
                ('length_les', models.FloatField()),
                ('version_les', models.CharField(max_length=8, null=True)),
                ('comment_les', models.CharField(max_length=64, null=True)),
                ('id_cc_les', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaching_app.CourseCategory')),
            ],
            options={
                'db_table': 'lessons',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id_stu', models.AutoField(primary_key=True, serialize=False)),
                ('name_stu', models.CharField(max_length=32)),
                ('sex_stu', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1)),
                ('age_stu', models.SmallIntegerField()),
                ('date_entry_stu', models.DateField()),
                ('state_stu', models.CharField(choices=[('0', '正常'), ('1', '补课'), ('2', '请假'), ('3', '毕业')], max_length=1)),
                ('comment_stu', models.CharField(max_length=256, null=True)),
                ('cur_les_stu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teaching_app.Lessons')),
                ('id_cc_stu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teaching_app.CourseCategory')),
                ('id_cla_stu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teaching_app.Classes')),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id_emp', models.AutoField(primary_key=True, serialize=False)),
                ('name_emp', models.CharField(max_length=32)),
                ('id_num_emp', models.CharField(max_length=18, unique=True)),
                ('tel_num_emp', models.CharField(max_length=12, unique=True)),
                ('supervisor_emp', models.IntegerField()),
                ('entry_date_emp', models.DateField()),
                ('ecp_emp', models.CharField(max_length=16, null=True)),
                ('ecpt_emp', models.CharField(max_length=12, null=True)),
                ('email_emp', models.EmailField(blank=True, max_length=254)),
                ('wechat_emp', models.CharField(max_length=64, null=True)),
                ('address_emp', models.CharField(max_length=128, null=True)),
                ('comment_emp', models.CharField(max_length=64, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaching_app.Departments')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.AddField(
            model_name='departments',
            name='supervisor_dep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='teaching_app.Employee', verbose_name='主管'),
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id_room', models.AutoField(primary_key=True, serialize=False)),
                ('name_room', models.CharField(max_length=32)),
                ('content_room', models.SmallIntegerField()),
                ('state_room', models.BooleanField()),
                ('comment_room', models.CharField(max_length=64, null=True)),
                ('campus_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaching_app.Campus')),
                ('warden_room', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='teaching_app.Employee')),
            ],
            options={
                'db_table': 'classroom',
            },
        ),
        migrations.AddField(
            model_name='classes',
            name='id_room_cla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teaching_app.Classroom'),
        ),
        migrations.AddField(
            model_name='classes',
            name='master_cla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='master_emp', to='teaching_app.Employee'),
        ),
        migrations.AddField(
            model_name='classes',
            name='teacher_cla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_emp', to='teaching_app.Employee'),
        ),
        migrations.AddField(
            model_name='campus',
            name='supervisor_cam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='teaching_app.Employee', verbose_name='主管'),
        ),
    ]
