# Generated by Django 2.2.5 on 2019-10-02 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        migrations.DeleteModel(
            name='Positions',
        ),
    ]
