# Generated by Django 2.2.5 on 2019-10-20 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='id_room_cla',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='master_cla',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='teacher_cla',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='campus_room',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='warden_room',
        ),
        migrations.RemoveField(
            model_name='departments',
            name='supervisor_dep',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='students',
            name='cur_les_stu',
        ),
        migrations.RemoveField(
            model_name='students',
            name='id_cc_stu',
        ),
        migrations.RemoveField(
            model_name='students',
            name='id_cla_stu',
        ),
        migrations.DeleteModel(
            name='Campus',
        ),
        migrations.DeleteModel(
            name='Classes',
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
