# Generated by Django 2.2.5 on 2019-10-02 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_app', '0002_auto_20191002_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='supervisor_dep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='teaching_app.Employee'),
        ),
    ]
