# Generated by Django 2.2.5 on 2019-10-02 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_app', '0003_auto_20191002_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='superior_dep',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='departments',
            name='supervisor_dep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='teaching_app.Employee'),
        ),
    ]
