# Generated by Django 2.2.5 on 2019-10-06 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_app', '0004_auto_20191002_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='comment_cam',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='supervisor_cam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='teaching_app.Employee'),
        ),
    ]
