# Generated by Django 2.2.5 on 2019-10-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='active',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='employee',
            name='degree',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='学历'),
        ),
        migrations.AddField(
            model_name='employee',
            name='major',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='专业'),
        ),
        migrations.AddField(
            model_name='employee',
            name='school',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='毕业学校'),
        ),
    ]
