# Generated by Django 2.2.5 on 2019-10-21 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sys_admin.Employee'),
        ),
    ]
