# Generated by Django 2.2.5 on 2019-10-20 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20191020_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_confirmed',
        ),
        migrations.DeleteModel(
            name='ConfirmString',
        ),
    ]
