# Generated by Django 2.2.5 on 2019-10-25 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20191021_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='emial',
            new_name='email',
        ),
    ]
